config:
  ## https://docs.fluentbit.io/manual/pipeline/outputs
  # https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master-es-default
        Logstash_Format On
        Retry_Limit False
        tls On
        tls.verify Off
        HTTP_User elastic
        HTTP_Passwd z991Z0GRfBlDPk0aH26893Gn
        Trace_Error On
        Buffer_Size False

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master-es-default
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        tls On
        tls.verify Off
        HTTP_User elastic
        HTTP_Passwd z991Z0GRfBlDPk0aH26893Gn
        Trace_Error On
        Buffer_Size False