image:
  tag: "2.0.3"

config:
  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 1GB

  # https://docs.fluentbit.io/manual/pipeline/outputs
  # https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master-es-default
        Logstash_Format Off
        Retry_Limit False
        tls On
        tls.verify Off
        HTTP_User elastic
        HTTP_Passwd vL4Bm216qJ94sVcS16kMS21X
        Suppress_Type_Name On
        Trace_Error On
        Replace_Dots On
        Generate_ID On

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master-es-default
        Logstash_Format Off
        Logstash_Prefix node
        Retry_Limit False
        tls On
        tls.verify Off
        HTTP_User elastic
        HTTP_Passwd vL4Bm216qJ94sVcS16kMS21X
        Suppress_Type_Name On
        Trace_Error On
        Replace_Dots On
        Generate_ID On
