apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-es
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - elasticsearch:
        host: elasticsearch-master-es-default
        port: 9200
        logstashFormat: true
        logstashPrefix: ks-logstash-log
        scheme: https
        password:
          valueFrom:
            secretKeyRef:
              key: password
              name: es-secret
        user:
          valueFrom:
            secretKeyRef:
              key: username
              name: es-secret