# https://github.com/rook/rook/blob/release-1.11/deploy/charts/rook-ceph/values.yaml
resources:
  limits:
    cpu: 0
    memory: 0
  requests:
    cpu: 0
    memory: 0
csi:
  csiRBDProvisionerResource: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-resizer
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-attacher
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-snapshotter
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-omap-generator
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : liveness-prometheus
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 100m
  csiRBDPluginResource: |
    - name : driver-registrar
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : liveness-prometheus
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
  csiCephFSProvisionerResource: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-resizer
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-attacher
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-snapshotter
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : liveness-prometheus
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
  csiCephFSPluginResource: |
    - name : driver-registrar
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : liveness-prometheus
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
  csiNFSProvisionerResource: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-nfsplugin
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
  csiNFSPluginResource: |
    - name : driver-registrar
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0
    - name : csi-nfsplugin
      resource:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: 0
          cpu: 0


# https://github.com/rook/rook/blob/release-1.11/deploy/charts/rook-ceph-cluster/values.yaml
# https://github.com/rook/rook/blob/release-1.11/deploy/examples/cluster-test.yaml
configOverride: |
    [global]
    osd_pool_default_size = 1
    mon_warn_on_pool_no_redundancy = false
    bdev_flock_retry = 20
    bluefs_buffered_io = false
    mon_data_avail_warn = 10
toolbox:
  enabled: true
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
cephClusterSpec:
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    port: 8080
    ssl: false
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: true
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  priorityClassNames:
    all: system-node-critical
    mgr: system-cluster-critical
  disruptionManagement:
    managePodBudgets: true
  resources:
    mgr:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    mon:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    osd:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    prepareosd:
      requests:
        cpu: "0"
        memory: "0"
    mgr-sidecar:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    crashcollector:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    logcollector:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    cleanup:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"

cephBlockPools:
  - name: ceph-blockpool
    # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md#spec for available configuration
    spec:
      failureDomain: host
      replicated:
        size: 1
        requireSafeReplicaSize: false
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      mountOptions: []
      # see https://github.com/rook/rook/blob/master/Documentation/ceph-block.md#provision-storage for available configuration
      parameters:
        imageFormat: "2"
        imageFeatures: layering
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

cephFileSystems:
  - name: ceph-filesystem
    # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md#filesystem-settings for available configuration
    spec:
      metadataPool:
        replicated:
          size: 1
          requireSafeReplicaSize: false
      dataPools:
        - failureDomain: host
          replicated:
            size: 1
            requireSafeReplicaSize: false
          name: data0
      metadataServer:
        activeCount: 1
        activeStandby: true
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        priorityClassName: system-cluster-critical
    storageClass:
      enabled: true
      isDefault: false
      name: ceph-filesystem
      pool: data0
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      mountOptions: []
      # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#provision-storage for available configuration
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

cephFileSystemVolumeSnapshotClass:
  enabled: false
  name: ceph-filesystem
  isDefault: true
  deletionPolicy: Delete
  annotations: {}
  labels: {}
  # see https://rook.io/docs/rook/latest/ceph-csi-snapshot.html#cephfs-snapshots for available configuration
  parameters: {}

cephBlockPoolsVolumeSnapshotClass:
  enabled: false
  name: ceph-block
  isDefault: false
  deletionPolicy: Delete
  annotations: {}
  labels: {}
  # see https://rook.io/docs/rook/latest/ceph-csi-snapshot.html#rbd-snapshots for available configuration
  parameters: {}

cephObjectStores:
  - name: ceph-objectstore
    # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Object-Storage/ceph-object-store-crd.md#object-store-settings for available configuration
    spec:
      metadataPool:
        failureDomain: host
        replicated:
          size: 1
          requireSafeReplicaSize: false
      dataPool:
        failureDomain: host
        replicated:
          size: 1
          requireSafeReplicaSize: false
      preservePoolsOnDelete: true
      gateway:
        port: 80
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        # securePort: 443
        # sslCertificateRef:
        instances: 1
        priorityClassName: system-cluster-critical
      healthCheck:
        bucket:
          interval: 60s
    storageClass:
      enabled: true
      name: ceph-bucket
      reclaimPolicy: Delete
      # see https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#storageclass for available configuration
