# https://github.com/rook/rook/blob/release-1.7/cluster/charts/rook-ceph-cluster/values.yaml
cephClusterSpec:
  dashboard:
    ssl: false

# https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph-cluster/templates/ingress.yaml
# doesnt work yet for kubernetes 1.22
#ingress:
#  dashboard:
#    annotations:
#      cert-manager.io/cluster-issuer: letsencrypt-prod
#      ingress.kubernetes.io/force-ssl-redirect: "true"
#      kubernetes.io/ingress.class: contour
#      kubernetes.io/tls-acme: "true"
#    host:
#      name: rook-ceph.selfmade4u.de
#      path: "/"
#    tls:
#      - hosts:
#          - rook-ceph.selfmade4u.de
#        secretName: rook-ceph.selfmade4u.de