config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host opensearch-cluster-master
        Logstash_Format On
        Retry_Limit False
    [OUTPUT]
        Name es
        Match host.*
        Host opensearch-cluster-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False