config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host opensearch-cluster-master
        Logstash_Format On
        Retry_Limit False
        tls On
        tls.verify Off
        HTTP_User admin
        HTTP_Passwd admin
        Suppress_Type_Name On
    [OUTPUT]
        Name es
        Match host.*
        Host opensearch-cluster-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        tls On
        tls.verify Off
        HTTP_User admin
        HTTP_Passwd admin
        Suppress_Type_Name On
