apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: observability
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jaeger-http
  namespace: observability
spec:
  parentRefs:
  - name: eg
    namespace: default
  hostnames:
  - "jaeger.selfmade4u.de"
  rules:
  - backendRefs:
    - name: simplest-query
      namespace: observability
      port: 16686
