ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    kubernetes.io/tls-acme: 'true'
  className: contour
  hosts:
    - host: support.selfmade4u.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: support.selfmade4u.de
      hosts:
        - support.selfmade4u.de

persistence:
  storageClass: rook-cephfs
  accessModes:
    - ReadWriteMany

elasticsearch:
  enabled: false # EATS ALL RAM + CPU
  enableInitialisation: false
  volumeClaimTemplate:
    storageClassName: rook-cephfs

envConfig:
  zammad:
    rails:
      livenessProbe: false
      readinessProbe: false
    nginx:
      livenessProbe: false
      readinessProbe: false
    websocket:
      livenessProbe: false
      readinessProbe: false

# if this works this would be nice https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
global:
  storageClass: rook-cephfs