# https://github.com/mastodon/mastodon/blob/main/chart/values.yaml
mastodon:
  createAdmin:
    enabled: true
    username: moritz_hedtke
    email: Moritz.Hedtke@t-online.de
  locale: de
  local_domain: mastodon.selfmade4u.de
  secrets:
    existingSecret: mastodon-secret
  persistence:
    assets:
      storageClassName: ceph-block
    system:
      storageClassName: ceph-block
ingress:
  tls:
    - hosts:
        - mastodon.selfmade4u.de
      secretName: selfmade4u.de-wildcard-certificate
  hosts:
   - host: mastodon.selfmade4u.de
     paths:
      - path: /
        pathType: Prefix
postgresql:
  auth:
    existingSecret: mastodon-secret
redis:
  auth:
    existingSecret: mastodon-secret
  replica:
    replicaCount: 0
elasticsearch:
  # TODO https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch#parameters
  enabled: false