# https://github.com/mastodon/mastodon/blob/main/chart/values.yaml
mastodon:
#  createAdmin:
#    enabled: true
#    username: moritz_hedtke
#    email: Moritz.Hedtke@t-online.de
#  locale: de
  local_domain: mastodon.selfmade4u.de
  secrets:
    existingSecret: mastodon-secret
  persistence:
    assets:
      storageClassName: ceph-block
    system:
      storageClassName: ceph-block
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"

  tls:
    - hosts:
        - mastodon.selfmade4u.de
      secretName: selfmade4u.de-wildcard-certificate
  hosts:
   - host: mastodon.selfmade4u.de
     paths:
      - path: /
        pathType: Prefix
postgresql:
  auth:
    existingSecret: mastodon-secret
redis:
  auth:
    existingSecret: mastodon-secret
elasticsearch:
  # TODO https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch#parameters
  enabled: false