# https://github.com/mastodon/mastodon/blob/main/chart/values.yaml
mastodon:
  createAdmin:
    enabled: true
    username: moritz_hedtke
    email: Moritz.Hedtke@t-online.de
  locale: de
  local_domain: mastodon.selfmade4u.de
  secrets:
    existingSecret: mastodon-secret
  persistence:
    assets:
      storageClassName: local-path
    system:
      storageClassName: local-path
ingress: # https://github.com/istio/istio/issues/26883
  annotations:
    kubernetes.io/ingress.class: istio
  tls:
    - hosts:
        - mastodon.selfmade4u.de
      secretName: selfmade4u.de-wildcard-certificate
  hosts:
   - host: mastodon.selfmade4u.de
     paths:
      - path: /
        pathType: Prefix
postgresql:
  auth:
    existingSecret: mastodon-secret
redis:
  auth:
    existingSecret: mastodon-secret
elasticsearch:
  # TODO https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch#parameters
  enabled: false
jobAnnotations:
  sidecar.istio.io/inject: "false"