apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-http
  namespace: argocd
spec:
  parentRefs:
  - name: eg
    namespace: default
  hostnames:
  - "argocd.selfmade4u.de"
  rules:
  - backendRefs:
    - name: argo-cd-argocd-server
      namespace: argocd
      port: 443
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-applicationset-controller-http
  namespace: argocd
spec:
  parentRefs:
  - name: eg
    namespace: default
  hostnames:
  - "argocd-applicationset-controller.selfmade4u.de"
  rules:
  - backendRefs:
    - name: argo-cd-argocd-applicationset-controller
      namespace: argocd
      port: 7000
