apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: projektwahl
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: projektwahl
        repo: projektwahl-lit
  template:
    metadata:
      name: 'projektwahl-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/projektwahl/projektwahl-lit.git'
        targetRevision: '{{head_sha}}' # for security use `main` here
        path: helm/
        helm:
          parameters:
          - name: "image.tag"
            value: "pull-{{head_sha}}"
          - name: "gateway.hostnames[0]"
            value: "projektwahl-2.selfmade4u.de"
      project: "projektwahl"
      destination:
        server: https://kubernetes.default.svc
        namespace: projektwahl
