apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: harbor-http
  namespace: harbor
spec:
  parentRefs:
  - name: eg
    namespace: default
  hostnames:
  - "harbor.selfmade4u.de"
  rules:
  - backendRefs:
    - name: harbor
      namespace: harbor
      port: 80
