global:
  defaultResources:
    requests:
      cpu: "0"
pilot:
  autoscaleEnabled: false
  resources:
    requests:
      cpu: "0"
      memory: "0"
proxy:
 resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "0"
      memory: "0"