apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  http-protocol: enabled # redirected breaks https service (maybe because of our config?)
  rollout-duration: "60"  # Value in seconds.
