
[package]
name = "function"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3"
actix-rt = "1"
log = "0.4.0"
env_logger = "0.7.1"
regex = "1.5.5"
tokio = "1.8.4"
actix-http = "2.2.1"

[dev-dependencies]
regex = "1.5.5"
tokio = "1.8.4"
actix-http = "2.2.1"
